
CREATE TABLE LOG_ALL(
	ID_LOG_ALL INT PRIMARY KEY AUTO_INCREMENT,
    ID_USER INT,
    LOG_DATE DATETIME,
    LOG VARCHAR(100)
);
DELIMITER $$
CREATE PROCEDURE INSERT_LOG_ALL(IN ID_USER INT, IN LOG_DATE DATETIME, IN LOG_TEXT VARCHAR(100), OUT ID_LOG_ALL INT)
BEGIN
	INSERT INTO LOG_ALL(ID_USER,LOG_DATE,LOG) VALUES(ID_USER,LOG_DATE,LOG_TEXT);
    SELECT LAST_INSERT_ID() INTO ID_LOG_ALL ;
END$$
DELIMITER ;